### PR TITLE
changes reflecting to the array

### PR DESCRIPTION
**Pull request by mohindar99**
By using the key word "memory" you are creating a different array and the changes made to it wont be reflecting to the present array . So changed to keyword "storage" where the new array is linked to previous array and any changes done to it would be reflected to the present array which is the requirement of that function.

### CODE REVIEW

**Comment by andreitoma8** [comment]
Hi, Mohidar! Thank you for taking the time to open the PR! The array is only read, but never written to in the function. It is only used to loop trought the stakers, so using `memory` instead of `storage` saves gas. Please let me know if you agree so I can close the PR.

**Comment by mohindar99** [comment]
Fine. Seems like the code has been updated a bit from the last time . Yeah seems fine to be .

**Comment by mohindar99** [comment]
I believe that adding events to the code makes it more feasible and easy data extraction for users and the owner .

**Comment by andreitoma8** [comment]
Even if the code would have not been changed, the `_stakers` array is never modified, so the changes don't matter. Here's the function from the changes you've proposed:
```solidity
function setRewardsPerHour(uint256 _newValue) public onlyOwner {
        address[] memory _stakers = stakersArray;
        uint256 len = _stakers.length;
        for (uint256 i; i < len; ++i) {
            address user = _stakers[i];
            stakers[user].unclaimedRewards += calculateRewards(user);
            stakers[msg.sender].timeOfLastUpdate = block.timestamp;
        }
        rewardsPerHour = _newValue;
    }

```

On the events comments, I 100% agree with you! Please feel free to open a separate PR if you would like to add comments to the contract, I believe everyone using this will be happy to have them.

**Comment by mohindar99** [comment]
yeah got it now . Will add events if possible in a separate PR. Thanks man !!!!

**Pull request closed without merging**
